In [251]:
## Importing required libraries
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [252]:
# Set the working directory
os.chdir('/Users/giorgiocavallo/Desktop/Python/coursera/IBM_data_analysis/Module_2')

# Get and print the new current working directory
current_directory = os.getcwd()
print(f"Current working directory: {current_directory}")

Current working directory: /Users/giorgiocavallo/Desktop/Python/coursera/IBM_data_analysis/Module_2

In [253]:
## read the csv data
import pandas as pd
df = pd.read_csv('laptop_pricing_dataset_mod1.csv')
df.head()

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837

In [254]:
## rounded screen size cm to nearest 2 decimal places
df['Screen_Size_cm'] = df['Screen_Size_cm'].round(1)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      238 non-null    int64
 1   Manufacturer    238 non-null    object
 2   Category        238 non-null    int64
 3   Screen          238 non-null    object
 4   GPU             238 non-null    int64
 5   OS              238 non-null    int64
 6   CPU_core        238 non-null    int64
 7   Screen_Size_cm  234 non-null    float64
 8   CPU_frequency   238 non-null    float64
 9   RAM_GB          238 non-null    int64
 10  Storage_GB_SSD  238 non-null    int64
 11  Weight_kg       233 non-null    float64
 12  Price           238 non-null    int64
dtypes: float64(3), int64(8), object(2)
memory usage: 24.3+ KB

## Task 1: Replace with Mean

In [255]:
print(df)

     Unnamed: 0 Manufacturer  Category     Screen  GPU  OS  CPU_core  \
0             0         Acer         4  IPS Panel    2   1         5
1             1         Dell         3    Full HD    1   1         3
2             2         Dell         3    Full HD    1   1         7
3             3         Dell         4  IPS Panel    2   1         5
4             4           HP         4    Full HD    2   1         7
..          ...          ...       ...        ...  ...  ..       ...
233         233       Lenovo         4  IPS Panel    2   1         7
234         234      Toshiba         3    Full HD    2   1         5
235         235       Lenovo         4  IPS Panel    2   1         5
236         236       Lenovo         3    Full HD    3   1         5
237         237      Toshiba         3    Full HD    2   1         5

     Screen_Size_cm  CPU_frequency  RAM_GB  Storage_GB_SSD  Weight_kg  Price
0              35.6            1.6       8             256       1.60    978
1              39.6            2.0       4             256       2.20    634
2              39.6            2.7       8             256       2.20    946
3              33.8            1.6       8             128       1.22   1244
4              39.6            1.8       8             256       1.91    837
..              ...            ...     ...             ...        ...    ...
233            35.6            2.6       8             256       1.70   1891
234            33.8            2.4       8             256       1.20   1950
235            30.5            2.6       8             256       1.36   2236
236            39.6            2.5       6             256       2.40    883
237            35.6            2.3       8             256       1.95   1499

[238 rows x 13 columns]

In [256]:
## Identify columns with missing values
missing_data = df.isnull().sum()
print(missing_data)

Unnamed: 0        0
Manufacturer      0
Category          0
Screen            0
GPU               0
OS                0
CPU_core          0
Screen_Size_cm    4
CPU_frequency     0
RAM_GB            0
Storage_GB_SSD    0
Weight_kg         5
Price             0
dtype: int64

In [257]:
## filter out columns with missing values
df_filtered = missing_data[missing_data > 0]
print(df_filtered)

Screen_Size_cm    4
Weight_kg         5
dtype: int64

## Task 2: Replace with Mean

Missing values in attributes that have continuous data are best replaced using Mean value. 
We note that values in "Weight_kg" attribute are continuous in nature, and some values are missing.
Therefore, write a code to replace the missing values of weight with the average value of the attribute.

In [258]:
df['Weight_kg'] = df['Weight_kg'].fillna(df['Weight_kg'].mean())

##### Replace with the most frequent value

Missing values in attributes that have categorical data are best replaced using the most 
frequent value. We note that values in "Screen_Size_cm" attribute are categorical in nature, 
and some values are missing. Therefore, write a code to replace the missing values of Screen Size with 
the most frequent value of the attribute.

In [259]:
df['Screen_Size_cm'] = df['Screen_Size_cm'].fillna(df['Screen_Size_cm'].mode())
## the dot allows you to chain multiple functions together in Pandas

## Task 3: Fixing the data types

Both "Weight_kg" and "Screen_Size_cm" are seen to have the data type "Object", 
while both of them should be having a data type of "float". Write a code to fix the data 
type of these two columns.

In [260]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      238 non-null    int64
 1   Manufacturer    238 non-null    object
 2   Category        238 non-null    int64
 3   Screen          238 non-null    object
 4   GPU             238 non-null    int64
 5   OS              238 non-null    int64
 6   CPU_core        238 non-null    int64
 7   Screen_Size_cm  234 non-null    float64
 8   CPU_frequency   238 non-null    float64
 9   RAM_GB          238 non-null    int64
 10  Storage_GB_SSD  238 non-null    int64
 11  Weight_kg       238 non-null    float64
 12  Price           238 non-null    int64
dtypes: float64(3), int64(8), object(2)
memory usage: 24.3+ KB
None

In [261]:
df['Weight_kg'] = df['Weight_kg'].astype(float)
df['Screen_Size_cm'] = df['Screen_Size_cm'].astype(float)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      238 non-null    int64
 1   Manufacturer    238 non-null    object
 2   Category        238 non-null    int64
 3   Screen          238 non-null    object
 4   GPU             238 non-null    int64
 5   OS              238 non-null    int64
 6   CPU_core        238 non-null    int64
 7   Screen_Size_cm  234 non-null    float64
 8   CPU_frequency   238 non-null    float64
 9   RAM_GB          238 non-null    int64
 10  Storage_GB_SSD  238 non-null    int64
 11  Weight_kg       238 non-null    float64
 12  Price           238 non-null    int64
dtypes: float64(3), int64(8), object(2)
memory usage: 24.3+ KB
None

# Task - 4

### Data Standardization
The value of Screen_size usually has a standard unit of inches. Similarly, weight of the laptop is needed to be in pounds. Use the below mentioned units of conversion and write a code to modify the columns of the dataframe accordingly. Update their names as well.

In [262]:
print(df.head(5))
df['Screen_Size_inches'] = df['Screen_Size_cm'] / 2.54
df.rename(columns={'Screen_Size_cm':'Screen_Size_inches'}, inplace=True)
df['Weight_pounds'] = df['Weight_kg'] * 2.20462
df.rename(columns={'Weight_kg':'Weight_pounds'}, inplace=True)
df.head(5)

   Unnamed: 0 Manufacturer  Category     Screen  GPU  OS  CPU_core  \
0           0         Acer         4  IPS Panel    2   1         5
1           1         Dell         3    Full HD    1   1         3
2           2         Dell         3    Full HD    1   1         7
3           3         Dell         4  IPS Panel    2   1         5
4           4           HP         4    Full HD    2   1         7

   Screen_Size_cm  CPU_frequency  RAM_GB  Storage_GB_SSD  Weight_kg  Price
0            35.6            1.6       8             256       1.60    978
1            39.6            2.0       4             256       2.20    634
2            39.6            2.7       8             256       2.20    946
3            33.8            1.6       8             128       1.22   1244
4            39.6            1.8       8             256       1.91    837

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inches,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Screen_Size_inches,Weight_pounds
0,0,Acer,4,IPS Panel,2,1,5,35.6,1.6,8,256,1.60,978,14.015748,3.527392
1,1,Dell,3,Full HD,1,1,3,39.6,2.0,4,256,2.20,634,15.590551,4.850164
2,2,Dell,3,Full HD,1,1,7,39.6,2.7,8,256,2.20,946,15.590551,4.850164
3,3,Dell,4,IPS Panel,2,1,5,33.8,1.6,8,128,1.22,1244,13.307087,2.689636
4,4,HP,4,Full HD,2,1,7,39.6,1.8,8,256,1.91,837,15.590551,4.210824

### Data Normalization
Often it is required to normalize a continuous data attribute. Write a code to normalize the "CPU_frequency" attribute with respect to the maximum value available in the dataset.

In [263]:
df['CPU_frequency'] = df['CPU_frequency'] / df['CPU_frequency'].max()

# Task - 5

### Binning
Binning is a process of creating a categorical attribute which splits the values of a continuous data into a specified number of groups. In this case, write a code to create 3 bins for the attribute "Price". These bins would be named "Low", "Medium" and "High". The new attribute will be named "Price-binned".

In [264]:
df.info()
bins = np.linspace(df['Price'].min(), df['Price'].max(), num = 4)
group_names = ['Low', 'Medium', 'High']
df['Price_binned'] = pd.cut(df['Price'], bins, labels = group_names, include_lowest = True)
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          238 non-null    int64
 1   Manufacturer        238 non-null    object
 2   Category            238 non-null    int64
 3   Screen              238 non-null    object
 4   GPU                 238 non-null    int64
 5   OS                  238 non-null    int64
 6   CPU_core            238 non-null    int64
 7   Screen_Size_inches  234 non-null    float64
 8   CPU_frequency       238 non-null    float64
 9   RAM_GB              238 non-null    int64
 10  Storage_GB_SSD      238 non-null    int64
 11  Weight_pounds       238 non-null    float64
 12  Price               238 non-null    int64
 13  Screen_Size_inches  234 non-null    float64
 14  Weight_pounds       238 non-null    float64
dtypes: float64(5), int64(8), object(2)
memory usage: 28.0+ KB

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inches,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Screen_Size_inches,Weight_pounds,Price_binned
0,0,Acer,4,IPS Panel,2,1,5,35.6,0.551724,8,256,1.60,978,14.015748,3.527392,Low
1,1,Dell,3,Full HD,1,1,3,39.6,0.689655,4,256,2.20,634,15.590551,4.850164,Low
2,2,Dell,3,Full HD,1,1,7,39.6,0.931034,8,256,2.20,946,15.590551,4.850164,Low
3,3,Dell,4,IPS Panel,2,1,5,33.8,0.551724,8,128,1.22,1244,13.307087,2.689636,Low
4,4,HP,4,Full HD,2,1,7,39.6,0.620690,8,256,1.91,837,15.590551,4.210824,Low

# Task - 6

### Indicator variables
Convert the "Screen" attribute of the dataset into 2 indicator variables, "Screen-IPS_panel" and "Screen-Full_HD". Then drop the "Screen" attribute from the dataset.

In [265]:
df['Screen'].unique() 
dummy_variable_1 = pd.get_dummies(df['Screen'])
dummy_variable_1.rename(columns={'IPS Panel':'Screen-IPS_Panel', 'Full HD':'Screen-Full_HD'}, inplace=True)
df = pd.concat([df, dummy_variable_1], axis = 1) # axis = 1 means column axis = 0 means row
# drop original column "Screen" from "df"
df.drop('Screen', axis = 1, inplace = True) ## axis = 1 means column axis = 0 means row    
df.head(5)

,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inches,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price,Screen_Size_inches,Weight_pounds,Price_binned,Screen-Full_HD,Screen-IPS_Panel
0,0,Acer,4,2,1,5,35.6,0.551724,8,256,1.60,978,14.015748,3.527392,Low,False,True
1,1,Dell,3,1,1,3,39.6,0.689655,4,256,2.20,634,15.590551,4.850164,Low,True,False
2,2,Dell,3,1,1,7,39.6,0.931034,8,256,2.20,946,15.590551,4.850164,Low,True,False
3,3,Dell,4,2,1,5,33.8,0.551724,8,128,1.22,1244,13.307087,2.689636,Low,False,True
4,4,HP,4,2,1,7,39.6,0.620690,8,256,1.91,837,15.590551,4.210824,Low,True,False

In [266]:
print(df.head())

   Unnamed: 0 Manufacturer  Category  GPU  OS  CPU_core  Screen_Size_inches  \
0           0         Acer         4    2   1         5                35.6
1           1         Dell         3    1   1         3                39.6
2           2         Dell         3    1   1         7                39.6
3           3         Dell         4    2   1         5                33.8
4           4           HP         4    2   1         7                39.6

   CPU_frequency  RAM_GB  Storage_GB_SSD  Weight_pounds  Price  \
0       0.551724       8             256           1.60    978
1       0.689655       4             256           2.20    634
2       0.931034       8             256           2.20    946
3       0.551724       8             128           1.22   1244
4       0.620690       8             256           1.91    837

   Screen_Size_inches  Weight_pounds Price_binned  Screen-Full_HD  \
0           14.015748       3.527392          Low           False
1           15.590551       4.850164          Low            True
2           15.590551       4.850164          Low            True
3           13.307087       2.689636          Low           False
4           15.590551       4.210824          Low            True

   Screen-IPS_Panel
0              True
1             False
2             False
3              True
4             False